[package]
name = "markymark-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
markymark-core = { path = "../markymark-core" }
tree-sitter = { workspace = true }
tree-sitter-markdown = { workspace = true }
tree-sitter-xml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
proptest = { workspace = true }
